"""ATTENTION! This module is autogenerated! Don't edit!"""

from protobuf.uprotobuf import Message, Field, Enum

PACKAGE='DeviceServerMessages'

class DeviceMessage(Message):
    _fields=[
        Field(name='device_id', type='UInt32', id=1, required=True),
        Field(name='iv', type='Bytes', id=2, required=True),
        Field(name='encrypted_payload', type='Bytes', id=3, required=True),
        Field(name='message_length', type='UInt32', id=4, required=True),
    ]
