"""ATTENTION! This module is autogenerated! Don't edit!"""

from protobuf.uprotobuf import Message, Field, Enum

PACKAGE='DeviceServerMessages'

class DeviceSettings(Message):
    _fields=[
        Field(name='measurement_interval_s', type='UInt32', id=1, required=True),
        Field(name='message_interval_s', type='UInt32', id=2, required=True),
        Field(name='warning_measurement_interval_s', type='UInt32', id=3, required=True),
        Field(name='warning_message_interval_s', type='UInt32', id=4, required=True),
        Field(name='warning_distance_mm', type='UInt32', id=5, required=True),
        Field(name='code_version', type='UInt32', id=6, required=True),
    ]
