"""ATTENTION! This module is autogenerated! Don't edit!"""

from protobuf.uprotobuf import Message, Field, Enum

PACKAGE='DeviceServerMessages'

class DeviceData(Message):
    class Measurements(Message):
        _fields=[
            Field(name='time_s', type='UInt32', id=1, required=True),
            Field(name='distance_mm', type='UInt32', id=2, required=True),
        ]

    _fields=[
        Field(name='battery_percentage', type='UInt32', id=1, required=True),
        Field(name='code_version', type='UInt32', id=2, required=True),
        Field(name='signal_strength', type='UInt32', id=3, required=True),
        Field(name='device_secret', type='UInt64', id=4, required=True),
        Field(name='measurements', type='Message', id=5, repeated=True, cls=Measurements),
    ]
